### ISSUE TITLE
Date and Time pickers not disappearing when selecting another date or time input

### ISSUE THREAD

**Issue by phpfui** [jockmac22/foundation_calendar_date_time_picker#23]
Jocko,
Great library!  It certainly seems to be filling a need.  I found an issue with it and I have a few suggestions for improvements.  I'm a JS novice, otherwise I would do a PR and fix them myself.

The bug is when you have an open date or time picker, and you click on another date or time input, the old picker stays open.  If you click on something other than a date or time input, the picker goes away as it should.  Once you click on something else with multiple pickers open, they all close.

Thanks.  I'll submit a couple of ideas in another ticket.

**Comment by watyeag** [comment]
I am seeing the same thing. I have two date picker fields back to back on my form, for a start date and end date. If I click the start date field and then click the end date field, the datepicker for the start date doesn't go away, it stays in the background. If I click anywhere else on the page it goes away.

**Comment by PHPFUI** [comment]
I found a better date picker for Foundation here: http://foundation-datepicker.peterbeno.com/example.html  Remember to disable it if you are on a mobile device, as you want the native date picker.  Desktop browsers are not as advanced, so you need a date picker.
