### ISSUE TITLE
The time picker should follow the data-time-format

### ISSUE THREAD

**Issue by phpfui** [jockmac22/foundation_calendar_date_time_picker#25]
If you use data-time-format="%H:%M" on an input control, the time picker still displays seconds and AM/PM.  If you specified "%H:%M %P", it should display the AM/PM in lower case (ideally).

**Comment by raihan2006i** [comment]
@phpfui and @jockmac22 I just started working on this issue fixing :slightly_smiling_face:  https://github.com/raihan2006i/foundation_calendar_date_time_picker/tree/issue-25. First quick fixing is working but i will double check later
