### ISSUE TITLE
The label for a null date lies

### ISSUE THREAD

**Issue by natematykiewicz** [jockmac22/foundation_calendar_date_time_picker#28]
foundation_calendar.js:89

When an input box has a null value and the picker is nullable, the default value for the label should read '--'. Instead, it has today's date in it, but the input box is never updated. This means that it appears to have today's value, but actually is empty. Calling setWorkingDate here is the problem. Returning a new Date makes sense because it needs to use today's date to build the calendar, but the value isn't set, so the label should read '--'.

``` javascript
getWorkingDate: function(opts) {
    var date_attr = opts.input.data('working-date');
    if (!date_attr || ('' + date_attr).length == 0) {
        date = new Date();
        this.setWorkingDate(opts, date, true); // Problem
    } else {
        date = this.getDateFromString(date_attr);
    }
    return date;
},
```

**Comment by Tommyixi** [comment]
@natematykiewicz Just wanted to thank you for this! Helped me out today :)
